In [1]:
weight_kg = 57.5

In [2]:
print(weight_kg)

57.5


In [3]:
print('weight in kilograms:', weight_kg)

weight in kilograms: 57.5


In [4]:
print('weight in pounds', weight_kg*2.2)

weight in pounds 126.50000000000001


In [5]:
weight_lb = weight_kg*2.2

In [6]:
weight_kg = 100

In [7]:
print('weight in kilograms:', weight_kg, 'and in pounds:', weight_lb)

weight in kilograms: 100 and in pounds: 126.50000000000001


In [8]:
%whos

Variable    Type     Data/Info
------------------------------
weight_kg   int      100
weight_lb   float    126.50000000000001


In [9]:
import numpy

In [10]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [11]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [12]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [13]:
print(type(data))

<class 'numpy.ndarray'>


In [14]:
print(data.dtype)

float64


In [15]:
data.astype('i')

array([[0, 0, 1, ..., 3, 0, 0],
       [0, 1, 2, ..., 1, 0, 1],
       [0, 1, 1, ..., 2, 1, 1],
       ..., 
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 2, 0],
       [0, 0, 1, ..., 1, 1, 0]], dtype=int32)

In [16]:
print(data.shape)

(60, 40)


In [18]:
print('first value in data:', data[0,0])

first value in data: 0.0


In [19]:
print('first value in data:', data[30,20])

first value in data: 13.0


In [22]:
print(data[0:4,0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


In [23]:
print(data[5:10,0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [24]:
print(data[5:10,:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [25]:
print(data[5:10,:])

[[  0.   0.   1.   2.   2.   4.   2.   1.   6.   4.   7.   6.   6.   9.
    9.  15.   4.  16.  18.  12.  12.   5.  18.   9.   5.   3.  10.   3.
   12.   7.   8.   4.   7.   3.   5.   4.   4.   3.   2.   1.]
 [  0.   0.   2.   2.   4.   2.   2.   5.   5.   8.   6.   5.  11.   9.
    4.  13.   5.  12.  10.   6.   9.  17.  15.   8.   9.   3.  13.   7.
    8.   2.   8.   8.   4.   2.   3.   5.   4.   1.   1.   1.]
 [  0.   0.   1.   2.   3.   1.   2.   3.   5.   3.   7.   8.   8.   5.
   10.   9.  15.  11.  18.  19.  20.   8.   5.  13.  15.  10.   6.  10.
    6.   7.   4.   9.   3.   5.   2.   5.   3.   2.   2.   1.]
 [  0.   0.   0.   3.   1.   5.   6.   5.   5.   8.   2.   4.  11.  12.
   10.  11.   9.  10.  17.  11.   6.  16.  12.   6.   8.  14.   6.  13.
   10.  11.   4.   6.   4.   7.   6.   3.   2.   1.   0.   0.]
 [  0.   1.   1.   2.   1.   3.   5.   3.   5.   8.   6.   8.  12.   5.
   13.   6.  13.   8.  16.   8.  18.  15.  16.  14.  12.   7.   3.   8.
    9.  11.   2.   5.   4.  

In [27]:
print(data[5,:])

[  0.   0.   1.   2.   2.   4.   2.   1.   6.   4.   7.   6.   6.   9.   9.
  15.   4.  16.  18.  12.  12.   5.  18.   9.   5.   3.  10.   3.  12.   7.
   8.   4.   7.   3.   5.   4.   4.   3.   2.   1.]


In [28]:
print(data[5:6,:])

[[  0.   0.   1.   2.   2.   4.   2.   1.   6.   4.   7.   6.   6.   9.
    9.  15.   4.  16.  18.  12.  12.   5.  18.   9.   5.   3.  10.   3.
   12.   7.   8.   4.   7.   3.   5.   4.   4.   3.   2.   1.]]


In [29]:
data[5,:] == data[5:6,:]


array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True]], dtype=bool)

In [31]:
doubledata = data * 2.0

In [32]:
print('original:')
print(data[:3,36:])
print('double:')
print(doubledata[:3,36:])

original:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
double:
[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]


In [33]:
tripledata = doubledata + data

In [35]:
print('original:')
print(data[:3,36:])
print('double:')
print(doubledata[:3,36:])
print('tripledata =')
print(tripledata[:3,36:])

original:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
double:
[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]
tripledata =
[[ 6.  9.  0.  0.]
 [ 3.  3.  0.  3.]
 [ 6.  6.  3.  3.]]


In [ ]:
print(tripledata[:3,36:]/2)